### ISSUE TITLE
What is the license of Atlas?

### ISSUE THREAD

**Issue by BrianAker** [openstack-atlas/atlas-lb#11]
Hi,

I was just looking through the code and I don't see license notices in some of the files/in the source root.

Can you clarify what the license is?

Thanks!
   -Brian

**Comment by youcef-laribi** [comment]
Hi Brian,

Thank you for pointing out this omission. The license is the Apache 2.0 license like for all OpenStack contributions. I have added a LICENSE file to the root directory of the project.

Thanks,
Youcef

**Comment by BrianAker** [comment]
Thanks for making that clear!

On Sep 14, 2012, at 12:00, Youcef Laribi notifications@github.com wrote:

Hi Brian,

Thank you for pointing out this omission. The license is the Apache 2.0
license like for all OpenStack contributions. I have added a LICENSE file
to the root directory of the project.

Thanks,
Youcef

—
Reply to this email directly or view it on
GitHubhttps://github.com/openstack-atlas/atlas-lb/issues/11#issuecomment-8572138.
